const vehicle = {
  'M6': {
    nationCard: 'USA',
    classCard: 'тт',
    cardCost: 4,
    cardResurs: 3,
    cardNationResurs: 0,
    cardAttack: 2,
    cardDefense: 2,
    cardAbilities: ['rep'],
  },
  'T1 Heavy Tank': {
    nationCard: 'USA',
    classCard: 'тт',
    cardCost: 4,
    cardResurs: 3,
    cardNationResurs: 0,
    cardAttack: 2,
    cardDefense: 2,
    cardAbilities: null,
  },
  'T29 E3': {
    nationCard: 'USA',
    classCard: 'тт',
    cardCost: 4,
    cardResurs: 3,
    cardNationResurs: 0,
    cardAttack: 2,
    cardDefense: 2,
    cardAbilities: ['cal'],
  },
  'T30': {
    nationCard: 'USA',
    classCard: 'тт',
    cardCost: 6,
    cardResurs: 5,
    cardNationResurs: 0,
    cardAttack: 2,
    cardDefense: 2,
    cardAbilities: ['inv'],
  },
  'T29': {
    nationCard: 'USA',
    classCard: 'тт',
    cardCost: 4,
    cardResurs: 3,
    cardNationResurs: 0,
    cardAttack: 2,
    cardDefense: 2,
    cardAbilities: ['rei'],
    countAbilRei: 2,
  },
  'T32': {
    nationCard: 'USA',
    classCard: 'тт',
    cardCost: 5,
    cardResurs: 4,
    cardNationResurs: 0,
    cardAttack: 2,
    cardDefense: 2,
    cardAbilities: ['rei'],
    countAbilRei: 3,
  },
  'T20': {
    nationCard: 'USA',
    classCard: 'ст',
    cardCost: 3,
    cardResurs: 2,
    cardNationResurs: 0,
    cardAttack: 1,
    cardDefense: 2,
    cardAbilities: ['sab'],
  },
  'M4 Sherman': {
    nationCard: 'USA',
    classCard: 'ст',
    cardCost: 3,
    cardResurs: 2,
    cardNationResurs: 0,
    cardAttack: 1,
    cardDefense: 2,
    cardAbilities: ['rep'],
  },
  'M7': {
    nationCard: 'USA',
    classCard: 'ст',
    cardCost: 3,
    cardResurs: 2,
    cardNationResurs: 0,
    cardAttack: 1,
    cardDefense: 2,
    cardAbilities: ['stu'],
    countAbilStu: 4,
  },
  'M2 Medium Tank': {
    nationCard: 'USA',
    classCard: 'ст',
    cardCost: 2,
    cardResurs: 1,
    cardNationResurs: 0,
    cardAttack: 1,
    cardDefense: 2,
    cardAbilities: null,
  },
  'M3 Lee': {
    nationCard: 'USA',
    classCard: 'ст',
    cardCost: 3,
    cardResurs: 2,
    cardNationResurs: 0,
    cardAttack: 1,
    cardDefense: 2,
    cardAbilities: ['rei'],
    countAbilRei: 1,
  },
  'M26 Pershing': {
    nationCard: 'USA',
    classCard: 'ст',
    cardCost: 3,
    cardResurs: 1,
    cardNationResurs: 0,
    cardAttack: 1,
    cardDefense: 2,
    cardAbilities: ['sto'],
  },
  'M36 Slugger': {
    nationCard: 'USA',
    classCard: 'пт',
    cardCost: 3,
    cardResurs: 2,
    cardNationResurs: 0,
    cardAttack: 2,
    cardDefense: 1,
    cardAbilities: ['int'],
  },
  'M10 Wolverine': {
    nationCard: 'USA',
    classCard: 'пт',
    cardCost: 3,
    cardResurs: 2,
    cardNationResurs: 0,
    cardAttack: 2,
    cardDefense: 1,
    cardAbilities: null,
  },
  'T1 Cunningham': {
    nationCard: 'USA',
    classCard: 'лт',
    cardCost: 1,
    cardResurs: 0,
    cardNationResurs: 0,
    cardAttack: 1,
    cardDefense: 1,
    cardAbilities: null,
  },
  'M5 Stuart': {
    nationCard: 'USA',
    classCard: 'лт',
    cardCost: 1,
    cardResurs: 0,
    cardNationResurs: 0,
    cardAttack: 1,
    cardDefense: 1,
    cardAbilities: ['rep'],
  },
  'M3 Stuart': {
    nationCard: 'USA',
    classCard: 'лт',
    cardCost: 1,
    cardResurs: 0,
    cardNationResurs: 0,
    cardAttack: 1,
    cardDefense: 1,
    cardAbilities: ['stu'],
    countAbilStu: 2,
  },
  'M37': {
    nationCard: 'USA',
    classCard: 'арт',
    cardCost: 2,
    cardResurs: 1,
    cardNationResurs: 0,
    cardAttack: 2,
    cardDefense: 1,
    cardAbilities: ['stu'],
    countAbilStu: 3,
  },
  'M41': {
    nationCard: 'USA',
    classCard: 'арт',
    cardCost: 2,
    cardResurs: 1,
    cardNationResurs: 0,
    cardAttack: 2,
    cardDefense: 1,
    cardAbilities: ['rei'],
    countAbilRei: 1,
  },
  'M12': {
    nationCard: 'USA',
    classCard: 'арт',
    cardCost: 3,
    cardResurs: 2,
    cardNationResurs: 0,
    cardAttack: 2,
    cardDefense: 1,
    cardAbilities: ['rei'],
    countAbilRei: 2,
  },
  'M7 Priest': {
    nationCard: 'USA',
    classCard: 'арт',
    cardCost: 3,
    cardResurs: 2,
    cardNationResurs: 0,
    cardAttack: 2,
    cardDefense: 1,
    cardAbilities: ['rep'],
  },
  'Bofors 40 mm': {
    nationCard: 'USA',
    classCard: 'всп',
    cardCost: 0,
    cardResurs: 0,
    cardNationResurs: 0,
    cardAttack: 1,
    cardDefense: 0,
    cardAbilities: null,
  },
  'Long Tom 155 mm': {
    nationCard: 'USA',
    classCard: 'всп',
    cardCost: 0,
    cardResurs: 0,
    cardNationResurs: 0,
    cardAttack: 1,
    cardDefense: 0,
    cardAbilities: ['cal'],
  },
  'M2 Mortar': {
    nationCard: 'USA',
    classCard: 'всп',
    cardCost: 0,
    cardResurs: 1,
    cardNationResurs: 0,
    cardAttack: 1,
    cardDefense: 0,
    cardAbilities: ['AB'],
  },
  'Airborne': {
    nationCard: 'USA',
    classCard: 'всп',
    cardCost: 0,
    cardResurs: 1,
    cardNationResurs: 0,
    cardAttack: 0,
    cardDefense: 0,
    cardAbilities: ['int', 'rei'],
    countAbilRei: 1,
  },
  // German
  'PzKpfw VI Tiger': {
    nationCard: 'German',
    classCard: 'тт',
    cardCost: 4,
    cardResurs: 3,
    cardNationResurs: 0,
    cardAttack: 2,
    cardDefense: 2,
    cardAbilities: null,
  },
  'PzKpfw VII Lowe': {
    nationCard: 'German',
    classCard: 'тт',
    cardCost: 5,
    cardResurs: 4,
    cardNationResurs: 0,
    cardAttack: 2,
    cardDefense: 2,
    cardAbilities: ['rep'],
  },
  'PzKpfw VIII Maus': {
    nationCard: 'German',
    classCard: 'тт',
    cardCost: 6,
    cardResurs: 5,
    cardNationResurs: 0,
    cardAttack: 2,
    cardDefense: 2,
    cardAbilities: ['inv'],
  },
  'PzKpfw VI-B Tiger II': {
    nationCard: 'German',
    classCard: 'тт',
    cardCost: 5,
    cardResurs: 4,
    cardNationResurs: 0,
    cardAttack: 2,
    cardDefense: 2,
    cardAbilities: ['rei'],
    countAbilRei: 3,
  },
  'VK3002 (DB)': {
    nationCard: 'German',
    classCard: 'ст',
    cardCost: 4,
    cardResurs: 3,
    cardNationResurs: 0,
    cardAttack: 1,
    cardDefense: 2,
    cardAbilities: ['sto'],
  },
  'PzKpfw IV': {
    nationCard: 'German',
    classCard: 'ст',
    cardCost: 3,
    cardResurs: 2,
    cardNationResurs: 0,
    cardAttack: 1,
    cardDefense: 2,
    cardAbilities: ['stu'],
    countAbilStu: 4,
  },
  'PzKpfw III/IV': {
    nationCard: 'German',
    classCard: 'ст',
    cardCost: 2,
    cardResurs: 1,
    cardNationResurs: 0,
    cardAttack: 1,
    cardDefense: 2,
    cardAbilities: null,
  },
  'VK3001 (P)': {
    nationCard: 'German',
    classCard: 'ст',
    cardCost: 4,
    cardResurs: 3,
    cardNationResurs: 0,
    cardAttack: 1,
    cardDefense: 2,
    cardAbilities: ['rep'],
  },
  'PzKpfw V Panther': {
    nationCard: 'German',
    classCard: 'ст',
    cardCost: 3,
    cardResurs: 2,
    cardNationResurs: 0,
    cardAttack: 1,
    cardDefense: 2,
    cardAbilities: ['rei'],
    countAbilRei: 2,
  },
  'PzKpfw II C': {
    nationCard: 'German',
    classCard: 'лт',
    cardCost: 1,
    cardResurs: 0,
    cardNationResurs: 0,
    cardAttack: 1,
    cardDefense: 1,
    cardAbilities: ['rei'],
    countAbilRei: 1,
  },
  'PzKpfw II J': {
    nationCard: 'German',
    classCard: 'лт',
    cardCost: 1,
    cardResurs: 0,
    cardNationResurs: 0,
    cardAttack: 1,
    cardDefense: 1,
    cardAbilities: ['stu'],
    countAbilStu: 2,
  },
  'PzKpfw II F': {
    nationCard: 'German',
    classCard: 'лт',
    cardCost: 1,
    cardResurs: 0,
    cardNationResurs: 0,
    cardAttack: 1,
    cardDefense: 1,
    cardAbilities: ['rep'],
  },
  'PzKpfw II Luchs': {
    nationCard: 'German',
    classCard: 'лт',
    cardCost: 1,
    cardResurs: 0,
    cardNationResurs: 0,
    cardAttack: 1,
    cardDefense: 1,
    cardAbilities: ['int'],
  },
  'PzKpfw 38(t)': {
    nationCard: 'German',
    classCard: 'лт',
    cardCost: 1,
    cardResurs: 0,
    cardNationResurs: 0,
    cardAttack: 1,
    cardDefense: 1,
    cardAbilities: null,
  },
  'Stug III': {
    nationCard: 'German',
    classCard: 'пт',
    cardCost: 3,
    cardResurs: 2,
    cardNationResurs: 0,
    cardAttack: 2,
    cardDefense: 1,
    cardAbilities: ['cal'],
  },
  'Jagdpanther': {
    nationCard: 'German',
    classCard: 'пт',
    cardCost: 4,
    cardResurs: 3,
    cardNationResurs: 0,
    cardAttack: 2,
    cardDefense: 1,
    cardAbilities: ['cal'],
  },
  'Marder II': {
    nationCard: 'German',
    classCard: 'пт',
    cardCost: 2,
    cardResurs: 1,
    cardNationResurs: 0,
    cardAttack: 2,
    cardDefense: 1,
    cardAbilities: ['sab'],
  },
  'Jagdpanzer IV': {
    nationCard: 'German',
    classCard: 'пт',
    cardCost: 4,
    cardResurs: 3,
    cardNationResurs: 0,
    cardAttack: 2,
    cardDefense: 1,
    cardAbilities: ['stu'],
    countAbilStu: 5,
  },
  'Ferdinand': {
    nationCard: 'German',
    classCard: 'пт',
    cardCost: 5,
    cardResurs: 4,
    cardNationResurs: 0,
    cardAttack: 2,
    cardDefense: 1,
    cardAbilities: ['rei'],
    countAbilRei: 3,
  },
  'Hummel': {
    nationCard: 'German',
    classCard: 'арт',
    cardCost: 3,
    cardResurs: 2,
    cardNationResurs: 0,
    cardAttack: 2,
    cardDefense: 1,
    cardAbilities: null,
  },
  'Sturmpanzer II': {
    nationCard: 'German',
    classCard: 'арт',
    cardCost: 2,
    cardResurs: 1,
    cardNationResurs: 0,
    cardAttack: 2,
    cardDefense: 1,
    cardAbilities: ['rep'],
  },
  'Sturmpanzer I': {
    nationCard: 'German',
    classCard: 'арт',
    cardCost: 2,
    cardResurs: 1,
    cardNationResurs: 0,
    cardAttack: 2,
    cardDefense: 1,
    cardAbilities: null,
  },
  'Sturmpanzer 38(t) Grille': {
    nationCard: 'German',
    classCard: 'арт',
    cardCost: 2,
    cardResurs: 1,
    cardNationResurs: 0,
    cardAttack: 2,
    cardDefense: 1,
    cardAbilities: ['rei'],
    countAbilRei: 1,
  },
  'Opel Blitz': {
    nationCard: 'German',
    classCard: 'всп',
    cardCost: 0,
    cardResurs: null,
    cardNationResurs: 4,                       // !!!!!!!!!!!
    cardAttack: 0,
    cardDefense: 1,
    cardAbilities: null,
  },
  'Nachrichtenbrigade': {
    nationCard: 'German',
    classCard: 'всп',
    cardCost: 0,
    cardResurs: 1,
    cardNationResurs: 0,
    cardAttack: 0,
    cardDefense: 0,
    cardAbilities: ['int', 'sto'],
  },
  // France
  'B1': {
    nationCard: 'France',
    classCard: 'тт',
    cardCost: 4,
    cardResurs: 3,
    cardNationResurs: 0,
    cardAttack: 2,
    cardDefense: 2,
    cardAbilities: null,
  },
  'AMX M4': {
    nationCard: 'France',
    classCard: 'тт',
    cardCost: 6,
    cardResurs: 5,
    cardNationResurs: 0,
    cardAttack: 2,
    cardDefense: 2,
    cardAbilities: ['inv'],
  },
  'ARL 44': {
    nationCard: 'France',
    classCard: 'тт',
    cardCost: 5,
    cardResurs: 4,
    cardNationResurs: 0,
    cardAttack: 2,
    cardDefense: 2,
    cardAbilities: ['rei'],
    countAbilRei: 3,
  },
  'Renault G1R': {
    nationCard: 'France',
    classCard: 'ст',
    cardCost: 3,
    cardResurs: 2,
    cardNationResurs: 0,
    cardAttack: 1,
    cardDefense: 2,
    cardAbilities: ['rei'],
    countAbilRei: 3,
  },
  'D2': {
    nationCard: 'France',
    classCard: 'ст',
    cardCost: 3,
    cardResurs: 2,
    cardNationResurs: 0,
    cardAttack: 1,
    cardDefense: 2,
    cardAbilities: null,
  },
  'Lorraine 40t': {
    nationCard: 'France',
    classCard: 'ст',
    cardCost: 3,
    cardResurs: 2,
    cardNationResurs: 0,
    cardAttack: 1,
    cardDefense: 2,
    cardAbilities: ['sto'],
  },
  'Bat Chatillon 25t': {
    nationCard: 'France',
    classCard: 'ст',
    cardCost: 3,
    cardResurs: 2,
    cardNationResurs: 0,
    cardAttack: 1,
    cardDefense: 2,
    cardAbilities: ['rep'],
  },
  'AMX 13-90': {
    nationCard: 'France',
    classCard: 'лт',
    cardCost: 1,
    cardResurs: 1,
    cardNationResurs: 0,
    cardAttack: 1,
    cardDefense: 1,
    cardAbilities: ['cal'],
  },
  'Hotchkiss H38': {
    nationCard: 'France',
    classCard: 'лт',
    cardCost: 1,
    cardResurs: 0,
    cardNationResurs: 0,
    cardAttack: 1,
    cardDefense: 1,
    cardAbilities: ['rei'],
    countAbilRei: 1,
  },
  'AMX 40': {
    nationCard: 'France',
    classCard: 'лт',
    cardCost: 1,
    cardResurs: 0,
    cardNationResurs: 0,
    cardAttack: 1,
    cardDefense: 1,
    cardAbilities: ['stu'],
    countAbilStu: 2,
  },
  'Hotchkiss H39': {
    nationCard: 'France',
    classCard: 'лт',
    cardCost: 1,
    cardResurs: 0,
    cardNationResurs: 0,
    cardAttack: 1,
    cardDefense: 1,
    cardAbilities: ['rep'],
  },
  'Hotchkiss H35': {
    nationCard: 'France',
    classCard: 'лт',
    cardCost: 1,
    cardResurs: 0,
    cardNationResurs: 0,
    cardAttack: 1,
    cardDefense: 1,
    cardAbilities: ['cal'],
  },
  'AMX 13-75': {
    nationCard: 'France',
    classCard: 'лт',
    cardCost: 1,
    cardResurs: 1,
    cardNationResurs: 0,
    cardAttack: 1,
    cardDefense: 1,
    cardAbilities: ['rei'],
    countAbilRei: 1,
  },
  'D1': {
    nationCard: 'France',
    classCard: 'лт',
    cardCost: 1,
    cardResurs: 0,
    cardNationResurs: 0,
    cardAttack: 1,
    cardDefense: 1,
    cardAbilities: null,
  },
  'AMX 38': {
    nationCard: 'France',
    classCard: 'лт',
    cardCost: 1,
    cardResurs: 0,
    cardNationResurs: 0,
    cardAttack: 1,
    cardDefense: 1,
    cardAbilities: ['int'],
  },
  'Lorraine 37 LAC': {
    nationCard: 'France',
    classCard: 'пт',
    cardCost: 2,
    cardResurs: 1,
    cardNationResurs: 0,
    cardAttack: 2,
    cardDefense: 1,
    cardAbilities: ['sab'],
  },
  'Panzerjager 35R': {
    nationCard: 'France',
    classCard: 'пт',
    cardCost: 2,
    cardResurs: 1,
    cardNationResurs: 0,
    cardAttack: 2,
    cardDefense: 1,
    cardAbilities: ['rei'],
    countAbilRei: 2,
  },
  'AMX 13 FL 11': {
    nationCard: 'France',
    classCard: 'пт',
    cardCost: 2,
    cardResurs: 1,
    cardNationResurs: 0,
    cardAttack: 2,
    cardDefense: 1,
    cardAbilities: ['stu'],
    countAbilStu: 3,
  },
  'AMX 105': {
    nationCard: 'France',
    classCard: 'арт',
    cardCost: 3,
    cardResurs: 2,
    cardNationResurs: 0,
    cardAttack: 2,
    cardDefense: 1,
    cardAbilities: null,
  },
  'Renault BS': {
    nationCard: 'France',
    classCard: 'арт',
    cardCost: 2,
    cardResurs: 1,
    cardNationResurs: 0,
    cardAttack: 2,
    cardDefense: 1,
    cardAbilities: null,
  },
  'Lorraine 155': {
    nationCard: 'France',
    classCard: 'арт',
    cardCost: 3,
    cardResurs: 2,
    cardNationResurs: 0,
    cardAttack: 2,
    cardDefense: 1,
    cardAbilities: ['rep'],
  },
  'Lorraine 39 LAM': {
    nationCard: 'France',
    classCard: 'арт',
    cardCost: 2,
    cardResurs: 1,
    cardNationResurs: 0,
    cardAttack: 2,
    cardDefense: 1,
    cardAbilities: ['rep'],
  },
  'Canon de 155 mm': {
    nationCard: 'France',
    classCard: 'всп',
    cardCost: 0,
    cardResurs: 0,
    cardNationResurs: 0,
    cardAttack: 1,
    cardDefense: 0,
    cardAbilities: ['cal'],
  },
  'CT Classe Jaguar': {
    nationCard: 'France',
    classCard: 'всп',
    cardCost: 1,
    cardResurs: null,
    cardNationResurs: 5,          // !!!!!!!!!!!!!!!!
    cardAttack: 1,
    cardDefense: 0,
    cardAbilities: [],
  },
  'Troupes de marine': {
    nationCard: 'France',
    classCard: 'всп',
    cardCost: 0,
    cardResurs: 1,
    cardNationResurs: 0,
    cardAttack: 0,
    cardDefense: 0,
    cardAbilities: ['int', 'cal'],
  },
  // USSR
  'КВ-1С': {
    nationCard: 'USSR',
    classCard: 'тт',
    cardCost: 4,
    cardResurs: 3,
    cardNationResurs: 0,
    cardAttack: 2,
    cardDefense: 2,
    cardAbilities: ['rep'],
  },
  'КВ-220': {
    nationCard: 'USSR',
    classCard: 'тт',
    cardCost: 6,
    cardResurs: 5,
    cardNationResurs: 0,
    cardAttack: 2,
    cardDefense: 2,
    cardAbilities: ['inv'],
  },
  'КВ-2': {
    nationCard: 'USSR',
    classCard: 'тт',
    cardCost: 5,
    cardResurs: 4,
    cardNationResurs: 0,
    cardAttack: 2,
    cardDefense: 2,
    cardAbilities: ['rei'],
    countAbilRei: 3,
  },
  'T-28': {
    nationCard: 'USSR',
    classCard: 'ст',
    cardCost: 3,
    cardResurs: 2,
    cardNationResurs: 0,
    cardAttack: 1,
    cardDefense: 2,
    cardAbilities: ['sto'],
  },
  'T-44': {
    nationCard: 'USSR',
    classCard: 'ст',
    cardCost: 3,
    cardResurs: 2,
    cardNationResurs: 0,
    cardAttack: 1,
    cardDefense: 2,
    cardAbilities: ['rep'],
  },
  'T-34-85': {
    nationCard: 'USSR',
    classCard: 'ст',
    cardCost: 3,
    cardResurs: 2,
    cardNationResurs: 0,
    cardAttack: 1,
    cardDefense: 2,
    cardAbilities: ['rei'],
    countAbilRei: 2,
  },
  'T-54': {
    nationCard: 'USSR',
    classCard: 'ст',
    cardCost: 4,
    cardResurs: 3,
    cardNationResurs: 0,
    cardAttack: 1,
    cardDefense: 2,
    cardAbilities: ['rei', 'rep'],
    countAbilRei: 1,
  },
  'T-34': {
    nationCard: 'USSR',
    classCard: 'ст',
    cardCost: 3,
    cardResurs: 2,
    cardNationResurs: 0,
    cardAttack: 1,
    cardDefense: 2,
    cardAbilities: ['stu'],
    countAbilStu: 4,
  },
  'T-46': {
    nationCard: 'USSR',
    classCard: 'лт',
    cardCost: 1,
    cardResurs: 0,
    cardNationResurs: 0,
    cardAttack: 1,
    cardDefense: 1,
    cardAbilities: ['rei'],
    countAbilRei: 1,
  },
  'T-26': {
    nationCard: 'USSR',
    classCard: 'лт',
    cardCost: 1,
    cardResurs: 0,
    cardNationResurs: 0,
    cardAttack: 1,
    cardDefense: 1,
    cardAbilities: null,
  },
  'T-127': {
    nationCard: 'USSR',
    classCard: 'лт',
    cardCost: 1,
    cardResurs: 0,
    cardNationResurs: 0,
    cardAttack: 1,
    cardDefense: 1,
    cardAbilities: ['stu'],
    countAbilStu: 2,
  },
  'СУ-76': {
    nationCard: 'USSR',
    classCard: 'пт',
    cardCost: 2,
    cardResurs: 1,
    cardNationResurs: 0,
    cardAttack: 2,
    cardDefense: 1,
    cardAbilities: ['stu'],
    countAbilStu: 3,
  },
  'СУ-100': {
    nationCard: 'USSR',
    classCard: 'пт',
    cardCost: 4,
    cardResurs: 3,
    cardNationResurs: 0,
    cardAttack: 2,
    cardDefense: 1,
    cardAbilities: ['rei'],
    countAbilRei: 3,
  },
  'СУ-85': {
    nationCard: 'USSR',
    classCard: 'пт',
    cardCost: 3,
    cardResurs: 2,
    cardNationResurs: 0,
    cardAttack: 2,
    cardDefense: 1,
    cardAbilities: ['cal'],
  },
  'СУ-18': {
    nationCard: 'USSR',
    classCard: 'арт',
    cardCost: 2,
    cardResurs: 1,
    cardNationResurs: 0,
    cardAttack: 2,
    cardDefense: 1,
    cardAbilities: ['rei'],
    countAbilRei: 1,
  },
  'С-51': {
    nationCard: 'USSR',
    classCard: 'арт',
    cardCost: 4,
    cardResurs: 3,
    cardNationResurs: 0,
    cardAttack: 2,
    cardDefense: 1,
    cardAbilities: ['sab'],
  },
  'СУ-8': {
    nationCard: 'USSR',
    classCard: 'арт',
    cardCost: 2,
    cardResurs: 1,
    cardNationResurs: 0,
    cardAttack: 2,
    cardDefense: 1,
    cardAbilities: ['rep'],
  },
  'СУ-26': {
    nationCard: 'USSR',
    classCard: 'арт',
    cardCost: 2,
    cardResurs: 1,
    cardNationResurs: 0,
    cardAttack: 2,
    cardDefense: 1,
    cardAbilities: null,
  },
  'СУ-5': {
    nationCard: 'USSR',
    classCard: 'арт',
    cardCost: 2,
    cardResurs: 1,
    cardNationResurs: 0,
    cardAttack: 2,
    cardDefense: 1,
    cardAbilities: ['int'],
  },
  'СУ-14': {
    nationCard: 'USSR',
    classCard: 'арт',
    cardCost: 4,
    cardResurs: 3,
    cardNationResurs: 0,
    cardAttack: 2,
    cardDefense: 1,
    cardAbilities: ['rep'],
  },
  '19-К 45 мм': {
    nationCard: 'USSR',
    classCard: 'всп',
    cardCost: 0,
    cardResurs: 0,
    cardNationResurs: 0,
    cardAttack: 1,
    cardDefense: 0,
    cardAbilities: null,
  },
  'ТМ-57': {
    nationCard: 'USSR',
    classCard: 'всп',
    cardCost: 0,
    cardResurs: 1,
    cardNationResurs: 0,
    cardAttack: 2,
    cardDefense: 0,
    cardAbilities: ['AT'],
  },
  '53-К 45 мм': {
    nationCard: 'USSR',
    classCard: 'всп',
    cardCost: 0,
    cardResurs: 0,
    cardNationResurs: 0,
    cardAttack: 1,
    cardDefense: 0,
    cardAbilities: ['cal'],
  },
  'СМЕРШ': {
    nationCard: 'USSR',
    classCard: 'всп',
    cardCost: 0,
    cardResurs: 1,
    cardNationResurs: 0,
    cardAttack: 0,
    cardDefense: 0,
    cardAbilities: ['int', 'sab'],
  },
  'ЗИС-5': {
    nationCard: 'USSR',
    classCard: 'всп',
    cardCost: 0,
    cardResurs: null,
    cardNationResurs: 4,
    cardAttack: 0,
    cardDefense: 1,
    cardAbilities: null,
  },
  'У-2': {
    nationCard: 'USSR',
    classCard: 'всп',
    cardCost: 1,
    cardResurs: null,
    cardNationResurs: 6,
    cardAttack: 0,
    cardDefense: 0,
    cardAbilities: null,
  },
}

module.exports = vehicle;